site_name: Ember
site_description: Ember is a Web server written in Python 3 that serves vector and raster map tiles from MBTiles files
repo_url: https://github.com/flother/ember
nav:
    - Overview: 'index.md'
markdown_extensions:
  - smarty
  - admonition
theme:
  name: material
  font: false
  logo: assets/images/logo48.png
  favicon: assets/images/logo48.png
  features:
    - navigation.tabs
copyright: <a href="https://icons8.com/icon/18515/fire">Fire icon</a> from <a href="https://icons8.com/">Icons8</a>
