name: Build and deploy
on:
  push:
    branches:
      - master
jobs:
  documentation:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
